### ISSUE TITLE
Duping Items

### ISSUE THREAD

**Issue by MPNull** [chadalen/astraeus#29]
I just noticed when I drop i.e a five logs on the ground and I spam click to pickup them I get more logs than there is on the ground. So I can basically get more of the logs than I have.

**Comment by Joshua-F** [comment]
[This](https://github.com/Vult-R/Astraeus-Java-Framework/blob/c7268a6d442b657847859808f4e373f0745c0216/net/src/main/java/astraeus/net/packet/in/PickupGroundItemPacket.java#L67-L71) needs to check the item exists before adding the item to inventory since the item could be gone by the time the task is finished.

**Comment by chadalen** [comment]
Fixed bbc8f6f9a2c82c4f65836ad26da99cf65949e684
